### ISSUE TITLE
printing "Empty cache" when cache objects exists

### ISSUE THREAD

**Issue by bablukid** [47ng/next-cache-explorer#1]
Hello and thanks for this usefull library.

next-cache-explorer keep printing "Empty cache" when cache objects exists.

fetchCacheDir() seems to point to the correct directory (home/app/packages/next-front-core/.next/cache/fetch-cache).

the project is a monorepo project where packages/next-front-core is the root directory of the next app.

```
home/app/packages/next-front-core/.next/cache/fetch-cache# ls
08bc4426f881f18650590239c7ce8b1dc0df2ab34531d1232240f7ea9b70a402
407cc28cd7e98066196db214d5deea3ffeeed8f2478bb717337e9fbb8d23bb58
41e37323a3cc8a416ede4c0885ef07081b975a61c8f54e59260d333a5f47b071
556a39060d8e676d363cbfad5227ec091c0895b28baf7ae11561aae1285225e9
e1bfba3cc189f2d2937c9c957abb1333c55f9c3a0638bf1ba4c3979cc2087647
e8f52f2e7e3b62b78c04e2f8f4cd3a0ad0494b75d9a2f3868dbd84efffb9d850
```

**Comment by franky47** [comment]
This project isn't really maintained, I was toying with what could be done at the time with Next.js internals, but it broke quick after (they are internals, after all). I think the reason was that the manifest file that listed all the cache entry is no longer there.

There's another project you could try that seems more up-to-date: https://github.com/KajSzy/next-cache-toolbar
